name: MineTils
version: 0.2.0
author: SidGames5
main: net.mlgland.minetils.MineTils
api-version: 1.8
commands:
  mttest:
    description: "Tests the plugin"
    usage: "/mttest"
    aliases:
      - mtest
      - minetilstest
  kick:
    description: "Kicks a player"
    usage: "/kick <player> [reason]"
    aliases:
      - remove
  ban:
    description: "Bans a player"
    usage: "/ban <player> [reason]"
    aliases:
      - permban
  unban:
    description: "Unbans a banned player"
    usage: "/unban <player>"
    aliases:
      - pardon
  minetils:
    description: "Central command for minetils"
    usage: "/mt <command> [args]"
    aliases:
      - mt
      - mtils
      - minet
      - mts