name: MineTils
version: 0.2.0
author: SidGames5
main: net.mlgland.minetils.MineTils
api-version: 1.18
commands:
  mttest:
    description: "Tests the plugin"
    usage: "/mttest"
    aliases:
      - mtest
      - minetilstest
  minetils:
    description: "Central command for minetils"
    usage: "/mt <command> [args]"
    aliases:
      - mt
      - mtils
      - minet
      - mts