name: MineTils
version: 0.0.1
author: SidGames5
main: net.ddns.mlgland.minetils.MineTils
api-version: 1.8
commands:
  mttest:
    description: "Tests the plugin"
    usage: "/mttest"
    aliases:
      - mtest
      - minetilstest
  kick:
    description: "Kicks a player"
    usage: "/kick <player> [reason]"
    aliases:
      - remove
  ban:
    description: "Bans a player"
    usage: "/ban <player> [reason]"
    aliases:
      - permban
  unban:
    description: "Unbans a banned player"
    usage: "/unban <player>"
    aliases:
      - pardon